Feature/monitoring of sites
epfl-si/wp-ops pull request #344
Opened 2020-10-01 13:00 UTC by GregLeBarbar

2020-10-06 14:12 UTC, domq requested changes

2020-10-06 14:12 UTC, domq commented on ansible/roles/wordpress-instance/tasks/backup.yml
> +      restic -r {{ backup_restic_repo_files }} tag "$files_snapshot_id" \
Je ne sais pas exactement pourquoi, mais le résultat de ce changement est qu'il n'y a plus de tags `latest`...

2020-10-07 11:47 UTC, ponsfrilus commented on ansible/roles/wordpress-instance/tasks/backup.yml
> +      restic -r {{ backup_restic_repo_files }} tag "$files_snapshot_id" \
Fixed by af71410

2020-10-13 07:09 UTC, domq requested changes

2020-10-13 07:09 UTC, domq commented on ansible/roles/wordpress-openshift-namespace/vars/monitoring-vars.yml
> +_prometheus_secrets: "{{ lookup('file', '/keybase/team/epfl_wp_prod/ansible_prometheus_secrets.yml') | from_yaml }}"
Il faut mettre ces secrets sous Git — Cf. Les usages pré-existants de `| eyaml(eyaml_keys)`

2020-10-13 07:41 UTC, ponsfrilus commented on ansible/roles/wordpress-openshift-namespace/vars/monitoring-vars.yml
> +_prometheus_secrets: "{{ lookup('file', '/keybase/team/epfl_wp_prod/ansible_prometheus_secrets.yml') | from_yaml }}"
Please see 9c70989

2020-10-13 07:49 UTC, domq approved these changes

2020-10-13 07:49 UTC, domq commented on ansible/roles/wordpress-openshift-namespace/vars/secrets-prometheus-wwp.yml
> +prometheus_htpass: "\n{% for cred in prometheus.credentials %}\n          - \"{{ cred.user }}:{{ cred.pass | eyaml(eyaml_keys) | password_hash('bcrypt') }}\"\n{% endfor %}"
Est-ce qu'on arrive à déplacer ça ailleurs ?

2020-10-13 07:49 UTC, domq commented on ansible/roles/wordpress-openshift-namespace/vars/secrets-prometheus-wwp.yml
> +  # Note that due to padding bits within the encoding, the last character should always be one of [.Oeu]
Selon conversation, il semble que ça pourrait ne pas être nécessaire ?

2020-10-13 07:51 UTC, ponsfrilus commented on ansible/roles/wordpress-openshift-namespace/vars/secrets-prometheus-wwp.yml
> +prometheus_htpass: "\n{% for cred in prometheus.credentials %}\n          - \"{{ cred.user }}:{{ cred.pass | eyaml(eyaml_keys) | password_hash('bcrypt') }}\"\n{% endfor %}"
Please see 18b784c4376622f9c440b8a418e70a4f6f0cbe4b

2020-10-13 07:51 UTC, ponsfrilus commented on ansible/roles/wordpress-openshift-namespace/vars/secrets-prometheus-wwp.yml
> +  # Note that due to padding bits within the encoding, the last character should always be one of [.Oeu]
Please see 18b784c4376622f9c440b8a418e70a4f6f0cbe4b

2020-10-13 07:53 UTC, merged