Feature/backup job template
epfl-si/wp-ops pull request #347
Opened 2020-10-02 15:37 UTC by ponsfrilus

2020-10-05 07:37 UTC, jdelasoie requested changes

2020-10-05 07:37 UTC, jdelasoie commented on ansible/roles/awx-instance/tasks/job-templates.yml
> +  tags: awx.bt
je serai plus pour respecter la hiérarchie existante (et également un peu plus verbeux, et je parle pas du \n ;) )
```suggestion
  tags: awx.job-template.backups-template
  
```

2020-10-05 07:37 UTC, jdelasoie commented on ansible/roles/awx-instance/tasks/job-templates.yml
> +      with AnsibleGetOrCreate(JobTemplate, name="Backup") as jt:
je vois que tu as utiliser directement AnsibleGetOrCreate, au lieu de la technique `update_json_status(changed=get_or_create_job_template(**kwarg))`

De mémoire, j'avais utiliser la seconde car c'était le seul moyen d'avoir un retour sur l'état de changement. Est-ce que ta technique gère l'état de changement (à savoir le jaune et vert comme résultat de la commande Ansible) ?

2020-10-06 06:27 UTC, ponsfrilus commented on ansible/roles/awx-instance/tasks/job-templates.yml
> +  tags: awx.bt
Fixed in defd528

2020-10-06 06:27 UTC, ponsfrilus commented on ansible/roles/awx-instance/tasks/job-templates.yml
> +      with AnsibleGetOrCreate(JobTemplate, name="Backup") as jt:
Absolument — jaune lors de la création, puis vert ensuite.

2020-10-06 07:09 UTC, jdelasoie approved these changes

2020-10-06 07:09 UTC, jdelasoie commented on ansible/roles/awx-instance/tasks/job-templates.yml
> +  tags: awx.job-template.backups
```suggestion
  tags: awx.job-template.backups
  
```
sinon c'est tout bon

2020-10-06 07:34 UTC, ponsfrilus commented
Merci Julien :)

2020-10-06 07:35 UTC, merged